
<<include colors_fonts_patterns.conf>>

<colors>
blue4    = 109,109,255
blue3    = 146,146,255
blue2    = 182,182,255
blue1    = 219,219,255
red1     = 255,219,219
red2     = 255,182,182
red3     = 255,146,146
red4     = 255,109,109
</colors>

<<include ideogram.conf>>
<<include ticks.conf>>

<image>
<<include etc/image.conf>>
</image>

karyotype   = karyotype.txt

chromosomes_units           = 1

chromosomes_display_default = yes
track_width = 0.1
track_pad   = 0.02
track_start = 1.2



<plots>

<plot>
file  = slices.txt
type  = highlight
r0    = dims(ideogram,radius_inner)
r1    = dims(ideogram,radius_outer)
fill_color       = undef
stroke_color     = white
stroke_thickness = 5
</plot>

<plot>
type    = heatmap

file             = SHm.txt
stroke_thickness = 1
stroke_color     = black
min              = 0
max              = 1
r1      = 0.95r
r0      = 0.84r
</plot>

<plot>
type    = heatmap

file             = lGHm.txt
stroke_thickness = 1
stroke_color     = black
min              = 0
max              = 1
r1      = 0.84r
r0      = 0.73r
</plot>

<plot>
type    = heatmap

file             = eGHm.txt
stroke_thickness = 1
stroke_color     = black
min              = 0
max              = 1
r1      = 0.73r
r0      = 0.62r
</plot>

<plot>
type    = heatmap

file             = normalHm.txt
stroke_thickness = 1
stroke_color     = black
min              = 0
max              = 1
r1      = 0.62r
r0      = 0.51r
</plot>

<plot>

type = scatter
file = genes1.txt

r0   = 0.89r
r1   = 0.89r

glyph = circle

stroke_color     = black
stroke_thickness = 2
 
</plot>

<plot>

type = scatter
file = genes2.txt

r0   = 0.78r
r1   = 0.78r

glyph = circle

stroke_color     = black
stroke_thickness = 2
 
</plot>

<plot>

type = scatter
file = genes3.txt

r0   = 0.67r
r1   = 0.67r

glyph = circle

stroke_color     = black
stroke_thickness = 2
 
</plot>

<plot>

type = scatter
file = genes4.txt

r0   = 0.56r
r1   = 0.56r

glyph = circle

stroke_color     = black
stroke_thickness = 2
 
</plot>

<plot>
# gene labels

type = text
file = genes.txt

r0   = 1.01r
r1   = 1.5r

label_size     = 48
label_font     = bold

</plot>

</plots>

<<include etc/housekeeping.conf>>
data_out_of_range* = trim

<links>

<link>

flat   = yes
ribbon = yes
crest  = 0.5
file   = ribbon.twist.txt

radius        = 0.5r
bezier_radius = 0.25r

stroke_color     = white
stroke_thickness = 1

</link>

</links>
